# Generated by Django 6.0.1 on 2026-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
