# Generated by Django 6.0.3 on 2026-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_location_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
